(() => {
  'use strict';
  const CFG={repo:'mynotebook',dir:'02_techo'};
  const $=id=>document.getElementById(id);
  const pad=n=>String(n).padStart(2,'0');
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'})[c]);
  const textOnly=v=>String(v||'').replace(/\[\[([^\]|]+)\|([^\]]+)\]\]/g,'$2').replace(/\[\[([^\]]+)\]\]/g,'$1');
  function jstParts(){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const g=t=>Number(p.find(x=>x.type===t)?.value||0);return{year:g('year'),month:g('month'),day:g('day')}}
  function parseItem(raw){let text=raw.trim(),checked=false;const task=/^\[([ xX/])\]\s*(.*)$/.exec(text);if(task){checked=/[xX]/.test(task[1]);text=task[2].trim()}const time=/^(\d{1,2}:\d{2})(?:\s*(?:-|–|—|〜|~)\s*(\d{1,2}:\d{2}))?\s+(.*)$/.exec(text);return time?{title:textOnly(time[3].trim()),time:time[2]?`${time[1]}–${time[2]}`:time[1],checked}:{title:textOnly(text),time:'',checked}}
  function parseMonth(markdown,month){const days=new Map(),monthUndated=[];let currentDay=null,currentWeek=null,section='none';for(const raw of markdown.split(/\r?\n/)){const line=raw.trimEnd();if(/^#\s+\d{4}年\d{1,2}月\s*$/.test(line)){currentDay=null;currentWeek=null;section='none';continue}const week=/^##\s+week(\d+)\s*$/i.exec(line);if(week){currentDay=null;currentWeek=Number(week[1]);section='week';continue}const day=/^##\s+(\d{1,2})月(\d{1,2})日(?:\([^)]*\))?\s*$/.exec(line);if(day){currentDay=Number(day[1])===month?Number(day[2]):null;section=currentDay?'day':'none';if(currentDay&&!days.has(currentDay))days.set(currentDay,[]);continue}if(/^###\s+日付未定\s*$/.test(line)){currentDay=null;section=currentWeek==null?'month-undated':'week-undated';continue}if(/^#{1,6}\s+/.test(line)){currentDay=null;section='none';continue}const item=/^\s*-\s+(.*)$/.exec(raw);if(!item?.[1]?.trim())continue;if(section==='day'&&currentDay)days.get(currentDay).push(parseItem(item[1]));else if(section==='month-undated')monthUndated.push(parseItem(item[1]))}return{days,monthUndated}}
  function initialMonth(){const q=new URLSearchParams(location.search).get('month');const m=/^(\d{4})-(\d{2})$/.exec(q||'');if(m)return{year:Number(m[1]),month:Number(m[2])};try{const saved=JSON.parse(localStorage.getItem('cockpid.calendar.right-view.v1')||'null');const sm=/^(\d{4})-(\d{2})-\d{2}$/.exec(saved?.date||'');if(sm)return{year:Number(sm[1]),month:Number(sm[2])}}catch{}const t=jstParts();return{year:t.year,month:t.month}}
  let state=initialMonth();const monthKey=()=>`${state.year}-${pad(state.month)}`;
  function shiftMonth(delta){const d=new Date(Date.UTC(state.year,state.month-1+delta,1));state={year:d.getUTCFullYear(),month:d.getUTCMonth()+1};render()}
  async function render(){ $('monthLabel').textContent=`${state.year}.${pad(state.month)}`;history.replaceState(null,'',`${location.pathname}?month=${monthKey()}`);$('sourceStatus').textContent='READING';$('monthGrid').innerHTML='<div class="message">READING MONTH…</div>';$('undated').hidden=true;if(!token()){$('sourceStatus').textContent='TOKEN REQUIRED';$('monthGrid').innerHTML='<div class="message">GitHub token が必要です。</div>';return}try{const payload=await gh(`${CFG.dir}/${monthKey()}.md`,CFG.repo);if(!payload?.content)throw new Error('SOURCE NOT FOUND');const data=parseMonth(decode(payload.content),state.month);const first=new Date(Date.UTC(state.year,state.month-1,1));const offset=(first.getUTCDay()+6)%7;const daysInMonth=new Date(Date.UTC(state.year,state.month,0)).getUTCDate();const prevDays=new Date(Date.UTC(state.year,state.month-1,0)).getUTCDate();const total=Math.ceil((offset+daysInMonth)/7)*7;const weeks=total/7;$('monthGrid').style.setProperty('--weeks',weeks);const today=jstParts();const cells=[];for(let i=0;i<total;i++){const day=i-offset+1;if(day<1){cells.push(`<div class="day outside"><div class="day-head"><b>${prevDays+day}</b></div></div>`);continue}if(day>daysInMonth){cells.push(`<div class="day outside"><div class="day-head"><b>${day-daysInMonth}</b></div></div>`);continue}const items=data.days.get(day)||[];const isToday=today.year===state.year&&today.month===state.month&&today.day===day;const events=items.map(item=>`<div class="event${item.checked?' checked':''}">${item.time?`<time>${esc(item.time)}</time>`:''}${esc(item.title)}</div>`).join('');cells.push(`<section class="day${isToday?' today':''}"><div class="day-head"><b>${day}</b>${isToday?'<span class="today-tag">TODAY</span>':''}</div>${events}</section>`)}$('monthGrid').innerHTML=cells.join('');if(data.monthUndated.length){$('undated').hidden=false;$('undatedItems').innerHTML=data.monthUndated.map(item=>`<div class="undated-item${item.checked?' checked':''}">${esc(item.title)}</div>`).join('')}$('sourceStatus').textContent='TECHO LIVE'}catch(error){console.error(error);$('sourceStatus').textContent='READ ERROR';$('monthGrid').innerHTML='<div class="message">Techoを読み込めませんでした。</div>'}}
  $('prevMonth').addEventListener('click',()=>shiftMonth(-1));$('nextMonth').addEventListener('click',()=>shiftMonth(1));$('todayMonth').addEventListener('click',()=>{const t=jstParts();state={year:t.year,month:t.month};render()});render();
})();
