(() => {
  'use strict';
  const OWNER='plzsayyes3',REPO='gpts',BRANCH='main',DIR='projects',TOKEN_KEY='zen-note-github-token';
  const $=(id)=>document.getElementById(id); const list=$('projectList'),room=$('projectRoom'),count=$('projectCount'),summary=$('townSummary'),detail=$('detailContent'),detailState=$('detailState'),reload=$('reloadBtn'),msgTitle=$('messageTitle'),msgText=$('messageText');
  let projects=[],selected='';
  const esc=(v)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  async function api(url){const h={Accept:'application/vnd.github+json'},t=localStorage.getItem(TOKEN_KEY)||'';if(t)h.Authorization=`Bearer ${t}`;let r=await fetch(url,{headers:h});if(!r.ok&&t&&(r.status===403||r.status===404))r=await fetch(url,{headers:{Accept:'application/vnd.github+json'}});if(!r.ok)throw new Error(`GitHub ${r.status}`);return r.json()}
  function decode(v){const b=atob(String(v||'').replace(/\n/g,''));return new TextDecoder().decode(Uint8Array.from(b,c=>c.charCodeAt(0)))}
  function scalar(v){v=String(v??'').trim();if(!v)return'';if((v.startsWith('"')&&v.endsWith('"'))||(v.startsWith("'")&&v.endsWith("'")))return v.slice(1,-1);if(v==='true')return true;if(v==='false')return false;if(/^-?\d+(?:\.\d+)?$/.test(v))return Number(v);return v}
  function fm(md){const lines=String(md||'').replace(/^\uFEFF/,'').split(/\r?\n/);if(lines[0]!=='---')return{};const meta={};let arr='';for(let i=1;i<lines.length;i++){if(lines[i].trim()==='---')break;const a=/^\s+-\s+(.*)$/.exec(lines[i]);if(a&&arr){if(!Array.isArray(meta[arr]))meta[arr]=[];meta[arr].push(scalar(a[1]));continue}const p=/^([A-Za-z0-9_-]+):\s*(.*)$/.exec(lines[i]);if(!p)continue;if(!p[2].trim()){meta[p[1]]='';arr=p[1]}else{meta[p[1]]=scalar(p[2]);arr=''}}return meta}
  function candidate(e){return e.type==='file'&&e.name.endsWith('.md')&&!/^(index|repositories)\.md$/i.test(e.name)&&!/^PROJECT_/i.test(e.name)&&!/-\d{4}-\d{2}-\d{2}\.md$/i.test(e.name)}
  function todayKey(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
  function age(d){if(!/^\d{4}-\d{2}-\d{2}$/.test(String(d||'')))return 99;return Math.floor((Date.parse(todayKey()+'T00:00:00Z')-Date.parse(d+'T00:00:00Z'))/86400000)}
  function state(p){const raw=String(p.status||'').toLowerCase(),a=age(p.last_touched);if(/wait|hold|pause|pending|backstage/.test(raw))return a<=3?{key:'waiting',label:'待機中',say:'まち中…'}:{key:'paused',label:'ひとやすみ',say:'休憩中…'};if(p.desk===true||a<=1)return{key:'hot',label:'進行中',say:'制作中！'};if(a<=7)return{key:'active',label:'じわ進み',say:'考え中…'};return{key:'paused',label:'ひとやすみ',say:'休憩中…'}}
  function motivation(p){const a=age(p.last_touched);let n=a<=1?3:a<=7?2:1;if(String(p.commitment||'').toLowerCase()==='must')n=3;return n}
  function pace(p){const a=age(p.last_touched);return a<=1?90:a<=3?70:a<=7?50:a<=14?30:15}
  async function loadOne(e){const x=await api(`https://api.github.com/repos/${OWNER}/${REPO}/contents/${e.path}?ref=${BRANCH}`);if(!x.content)return null;const m=fm(decode(x.content));if(m.type!=='project'||m.status==='archived')return null;return{id:String(m.id||e.name.replace(/\.md$/,'')),title:String(m.title||m.id||e.name),...m,path:e.path}}
  function renderRoom(){room.innerHTML=projects.slice(0,6).map(p=>{const s=state(p);return `<button class="worker${selected===p.id?' active':''}" data-project-id="${esc(p.id)}" data-state="${s.key}"><span class="bubble">${s.say}</span><span class="person"><i class="hair"></i><i class="head"></i><i class="body"></i></span><span class="desk-pixel"><i class="monitor"></i></span><span class="worker-name">${esc(p.title)}</span></button>`}).join('')||'<div class="room-loading">Projectがありません</div>'}
  function renderList(){count.textContent=projects.length;list.innerHTML=projects.map(p=>{const s=state(p),pc=pace(p);return `<button class="project-row${selected===p.id?' active':''}" data-project-id="${esc(p.id)}"><span class="project-name">${esc(p.title)}</span><span class="state-chip">${s.label}</span><span class="meter" aria-label="pace ${pc}"><span style="width:${pc}%"></span></span></button>`}).join('')}
  function show(id){const p=projects.find(x=>x.id===id);if(!p)return;selected=id;const s=state(p),m=motivation(p),pc=pace(p),sheets=Math.max(0,Number(p.sheets||0));detailState.textContent=s.label;detail.innerHTML=`<div class="detail-head"><div><h2>${esc(p.title)}</h2><div class="detail-meta">最終更新 ${esc(p.last_touched||'—')}</div></div><span class="big-status">${s.label}</span></div><div class="stat-grid"><div class="stat"><b>勢い</b><strong>${pc}%</strong></div><div class="stat"><b>やる気</b><strong>${'★'.repeat(m)}${'☆'.repeat(3-m)}</strong></div><div class="stat"><b>SHEETS</b><strong>${sheets}</strong></div></div><div class="detail-block"><b>いま</b><p>${esc(p.current||'まだCurrentは書かれていません。')}</p></div><div class="detail-block"><b>つぎ</b><p>${esc(p.next||'まだNextは書かれていません。')}</p></div>`;msgTitle.textContent=`「${p.title}」は ${s.label}。`;msgText.textContent=s.key==='hot'?'いま触れているプロジェクト。勢いがあるうちに次の一手へ。':s.key==='waiting'?'止まっているのではなく、何かを待っている状態として置いておきます。':s.key==='active'?'少しずつ進んでいます。急がず、次に触る場所だけ見える状態です。':'いまは休ませているプロジェクト。必要になったらまた起こせます。';renderRoom();renderList()}
  async function load(){reload.disabled=true;summary.textContent='gpts / projects を読んでいます…';try{const es=await api(`https://api.github.com/repos/${OWNER}/${REPO}/contents/${DIR}?ref=${BRANCH}`);const xs=await Promise.all((Array.isArray(es)?es:[]).filter(candidate).map(async e=>{try{return await loadOne(e)}catch(err){console.warn('Project Town skip',e.path,err);return null}}));projects=xs.filter(Boolean).sort((a,b)=>String(b.last_touched||'').localeCompare(String(a.last_touched||'')));const active=projects.filter(p=>['hot','active'].includes(state(p).key)).length,waiting=projects.filter(p=>state(p).key==='waiting').length;summary.textContent=`進行 ${active} / 待機 ${waiting} / 全部 ${projects.length}`;renderRoom();renderList();if(projects[0])show(projects[0].id)}catch(err){console.error(err);summary.textContent=`読み込み失敗 · ${err.message||err}`;room.innerHTML='<div class="room-loading">Projectを読み込めませんでした</div>'}finally{reload.disabled=false}}
  document.addEventListener('click',e=>{const b=e.target.closest?.('[data-project-id]');if(b)show(b.dataset.projectId)});reload.addEventListener('click',load);load();
})();